### ISSUE TITLE
Pull items from databases using other characteristics

### ISSUE THREAD

**Issue by SupposeNot** [SupposeNot/RAMP#102]
It would be nice if a bunch of basic stuff was (1) precalculated in our databases and (2) we could pull all (known) polytopes matching various search criteria (e.g., all self dual polytopes of type {8,8}, all orientable polytopes of type {6,3,3}, etc.).

This might involve some detailed thought about how we want to store this stuff...

**Comment by CunningGabe** [comment]
Subsumed under #135.
