### ISSUE TITLE
Graph tests for polytopality

### ISSUE THREAD

**Issue by SupposeNot** [SupposeNot/RAMP#106]
E.g., something like ComponentIntersectionProperty or WeakPathIntersectionProperty or what have you...

**Comment by Mixer2021** [comment]
Check for polytopality for non-faithful maniplexes.
Could add IsFaithful, but might be computationally expensive.
Currently IsPolytopal uses SPIP (I think).

**Comment by CunningGabe** [comment]
Recalling our discussion of this earlier...
CIP, PIP, and SPIP are equivalent for faithful maniplexes, but possibly not in general. So it would be good to have all 3 of these. 

For IsFaithful (or whatever name we eventually give it), we should be able to do something like:
1. Check that all facets (i.e. subgraphs induced by removing edge label n-1) are faithful.
2. Check that r_{n-1} does not match within any facets.
As a base case, all 2-maniplexes are faithful. (They are polygons).

I think that should work, but I haven't written the details down carefully to check.

**Comment by Mixer2021** [comment]
Just reread the published version of Polytopality of Maniplexes.
It looks to me that CIP, SPIP, and WPIP (PIP) are all equivalent to IsPolytopal.
If I am reading it correctly, it does not depend on IsFaithful.

**Comment by CunningGabe** [comment]
OK, I double-checked too and you're absolutely right. 

Then I guess all we need to add is IsFaithful (or... "IsPosetable"? or something) since I think that's worth caring about independent of polytopality.
