### ISSUE TITLE
Universal SGGIs and their type

### ISSUE THREAD

**Issue by SupposeNot** [SupposeNot/RAMP#111]
Seems like we ought to be able to 

- Construct a polytope from a universal sggi and have the polytope know that its Schlafli symbol has some $$\infty$$s in ti.
- Have a tool for calculating the ... Schlafli symbol of an SGGI.

**Comment by SupposeNot** [comment]
```
gap> k := Sggi([infinity, infinity], [[], [2,3,2,3,2,3]]);;
gap> SchlafliSymbol(k);
```
Doesn't work, since RAMP doesn't currently know how to detect that infinity.

**Comment by CunningGabe** [comment]
In general this is "hard", but I made a few easy cases work now in 53e3ee0ea9a2f69e4257b3c3177ee4a65561599e:

```
gap> ReflexibleManiplex(UniversalSggi([3,5]));
reflexible 3-maniplex of type [ 3, 5 ] with 120 flags
gap> ReflexibleManiplex(UniversalSggi([3,infinity]));
reflexible 3-maniplex of type [ 3, infinity ] with infinity flags
gap> ReflexibleManiplex(UniversalSggi(3));
reflexible 3-maniplex of type [ infinity, infinity ] with infinity flags
```
