### ISSUE TITLE
Mix bug

### ISSUE THREAD

**Issue by SupposeNot** [SupposeNot/RAMP#125]
Mix construct the Reflexible Mix, not the mix.

Example code:
```
g3:=Maniplex(Group([(1,2),(1,2),(1,2)]));
no:=Maniplex(Group([(1,2)(3,4)(5,6)(7,8),(1,8)(2,3)(4,5)(6,7),(1,5)(2,6)(3,8)(4,7)]));
ono:=Mix(g3,no);
cono:=ConnectionGroup(ono);
MovedPoints(cono);
```
The result should be the orientable cover of `no`, but instead we get the reflexible orientable cover of `no`.

**Comment by Mixer2021** [comment]
Should be set now.

Mix now checks if both inputs are reflexible.  If so, it does a group mixing on their connection groups.
If not, it does a flag mix.
