### ISSUE TITLE
Famous graphs

### ISSUE THREAD

**Issue by SupposeNot** [SupposeNot/RAMP#128]
We should have eg:

- Heawood graph
- Peterson graph
- circulant graphs
- K_{n,m}
- etc.

**Comment by SupposeNot** [comment]
And as much Cayley graph stuff as we can manage

**Comment by Mixer2021** [comment]
https://github.com/jaanos/gap-graphs has quite a bit done for families of graphs.  Perhaps we don't need to reinvent the wheel.

Also CayleyGraph( G, gens ) is already in GRAPE.

**Comment by SupposeNot** [comment]
I guess we just need to make sure we can interoperate well.

**Comment by SupposeNot** [comment]
Have you been able to get this to load? I can't seem to...

**Comment by Mixer2021** [comment]
Hmmmm.  Nope something is not right.  Package is a bit old.  Let me look to see if it is implemented elsewhere.

**Comment by Mixer2021** [comment]
I don't see another good source. 
Should we just take/borrow what we need and somehow add the below copyright info?  Otherwise, I can make what we need from scratch without TOO much trouble.
The MIT License (MIT)
Copyright (c) 2014 Janoš Vidali

**Comment by SupposeNot** [comment]
Why don't we email him as ask what the development status is/what sort of acknowledgement he would like? The MIT license is _pretty_ generous in its terms. The only question mark in my mind is if it is possible to limit the applicability of the MIT stuff to the code we are using/modifying? I'm thinking we include that notice at the header of any file where we are directly incorporating his code, with a small additional header making it clear that the MIT license does not extend to the rest of the GAP project (we haven't decided on a license we want to use for this).

**Comment by Mixer2021** [comment]
Leaving this issue open.  On the first pass we now have:
Heawood graph
Peterson graph
circulant graphs
K_{n,m}

Can think about other graphs that we want to add, and put them here as needed.

**Comment by Mixer2021** [comment]
Closed for now.
