### ISSUE TITLE
Verify relation code

### ISSUE THREAD

**Issue by SupposeNot** [SupposeNot/RAMP#131]
Sometimes it would be nice to see if a string is a relation for a given maniplex's description. Right now I'm imagining this in the reflexible setting, but it would look something like this:
```
gap>m:=ReflexibleManiplex([8,6],"(r0 r1)^4 (r1 r2)^3");;
gap>IsRelationOfReflexibleManiplex(m,"(r0 r1 r2)^3");
```

Might also be good to just simplify a string in the group of a maniplex.

**Comment by Mixer2021** [comment]
For a general maniplex, I suppose we want to check this for the connection group?

**Comment by CunningGabe** [comment]
The code above now works as of 06d07b3cc051005c4dc066aa33b13cdc4ab7103d.

I could add something like SimplifiedSggiElement which would work like:
```
gap> c := Cube(3);;
gap> x := SimplifiedSggiElement(c, "(r0 r1)^5");
r0*r1
```
The only problem is that while I know how to accomplish that (by calling SetReducedMultiplication on the automorphism group before asking for SggiElement), I'm not sure how to turn it off. So once you call SimplifiedSggiElement on a particular Sggi/Maniplex, all future calculations with it will be slower. Is that okay?

**Comment by SupposeNot** [comment]
I think that's fine, as long as it is documented. Presumably, the IsRelationOfReflexibleManiplex doesn't have this problem?

**Comment by CunningGabe** [comment]
Correct. OK, I'll add SimplifiedSggiElement and put a warning in the documentation.

**Comment by CunningGabe** [comment]
Done in d01909f1d39e37b1d4df7faa1f4af05ed0a816c7.
