### ISSUE TITLE
Update the Readme-dev.md file

### ISSUE THREAD

**Issue by CunningGabe** [SupposeNot/RAMP#136]
It is quite out-of-date at this point, and it should be the first place we point people who want to make serious contributions.
(Though I think that since a lot of low-level code is now taken care of, many people ought to be able to contribute without digging into the arcane innards...)

Things to mention:
- [ ] How to set nice display / view / etc behavior
- [ ] Other things that I'll come back and write down when I have time to brainstorm

**Comment by SupposeNot** [comment]
Good enough
