### ISSUE TITLE
Make a release checklist

### ISSUE THREAD

**Issue by CunningGabe** [SupposeNot/RAMP#151]
There is a bunch of little administrative stuff that should be dealt with every time we make a new release, such as updating PackageInfo.g, running TEST_RAMP() to make sure we haven't broken anything, etc. We should start making a list of all those things as we think of them, and then run through the whole checklist before we make a new release. Maybe we want one shorter checklist for incremental releases and another for major milestones.

Probably it would be a good idea to do a 0.6.3 release soon - we've added some nice new functionality (voltage operations etc) and cleaned up a bunch of minor issues.

**Comment by CunningGabe** [comment]
Here are a few other things for the checklist:
* Rebuild the pdf documentation. (I don't have latex set up properly, so I can update the html and inline but not the pdf.)
* Write release notes
* Check that new code is documented and tested

**Comment by SupposeNot** [comment]
Need to also develop/write the change log.

**Comment by SupposeNot** [comment]
Done
