### ISSUE TITLE
Odd Behavior of IsQuotient 

### ISSUE THREAD

**Issue by Mixer2021** [SupposeNot/RAMP#152]
A should be equal to B, and they both should be quotients of each other.  One direction is failing.
M:=Simplex(4);
W:=WythoffVoltageOperator(4,[0,1,2,3],M);
A:=Facets(W)[2];
B:=Prism(6);
Size(A)=Size(B);
A=B;
B=A;
IsQuotient(A,B);
IsQuotient(B,A);

**Comment by Mixer2021** [comment]
Issue shows up with FlagOrbitRepresentatives.  
For some reason when you call that function you gets a different result than when you run the code line by line on A.

Issue does not show up if you replace Facets with Facet
A:=Facet(W,145) works fine.

**Comment by CunningGabe** [comment]
Fixed in d9b69fac875a4eb8489049b525237f6d497d66eb.
