### ISSUE TITLE
Add SymmetryTypeGraph with respect to a subgroup of the automorphism group

### ISSUE THREAD

**Issue by CunningGabe** [SupposeNot/RAMP#153]
As it sounds - it's the quotient of a maniplex by a subgroup of the automorphism group.

**Comment by Mixer2021** [comment]
I think this already exists, but let me know if you were imagining something different.  Perhaps it is not well documented.

gap> M:=Cube(3);
Cube(3)
gap> A:=AutomorphismGroupOnFlags(M);
<permutation group with 3 generators>
gap> A2:=Group(A.1,A.2);
<permutation group with 2 generators>
gap> SymmetryTypeGraph(M,A2);
Edge labeled graph with 6 vertices, and edge labels [ 0, 1, 2 ]

**Comment by CunningGabe** [comment]
Ah, okay - yeah, it's not in the documentation so I missed it. So just an update to documentation is needed.

**Comment by CunningGabe** [comment]
Done in b72c883097f3d79eb6004106cdcb31000fc4bc7e.
