### ISSUE TITLE
Tests for internal and external self-duality

### ISSUE THREAD

**Issue by CunningGabe** [SupposeNot/RAMP#154]
c.f. my paper with Mark.

(Not to be confused with proper and improper self-duality, which is different)

**Comment by Mixer2021** [comment]
Do we want this for non-reflexible maniplexes?  We talked only about regular polytopes, but maybe this can be generalized at least to chiral?

**Comment by CunningGabe** [comment]
Yeah, I guess it makes sense for chiral - we can still ask whether the group automorphism that sends each s_i to s_{n-i}^-1 is inner or outer. So let's just do it for chiral and reflexible for now.

**Comment by Mixer2021** [comment]
Sounds good.  I will add this tomorrow.
Do we have the ability to grab the standard generators s_i if you are given a chiral maniplex?  
Normal AutomorphismGroup(M) won't give the appropriate gens.

**Comment by CunningGabe** [comment]
It depends on how the chiral maniplex was built - for example, anything built from RotaryManiplex should give those generators, but random maniplexes that are later discovered to be chiral will not.

For example, compare AutomorphismGroup(ToroidalMap44([1,2])) with AutomorphismGroup(ToroidalMap44([1,2],[-2,1])).

It shouldn't be hard to make AutomorphismGroup try to put the group of a chiral maniplex in a standard form. I'll add an issue for that.

**Comment by Mixer2021** [comment]
IsInternallySelfDual( M[, x] ) is done for the reflexible case, and is ready to go for chiral once the automorphism groups are well behaved.

**Comment by CunningGabe** [comment]
Done for chiral in 3c232bcecb2cc33737563b77dbb25aae1ddada7e.
