### ISSUE TITLE
Bug in the map operation "Lace"?

### ISSUE THREAD

**Issue by CunningGabe** [SupposeNot/RAMP#165]
Now that our code checks maniplexes to make sure they are actually maniplexes (and not pre-maniplexes), I noticed that one of the map operations might not be doing the right thing...

```
gap> M := Lace(Cube(3));
#I  The given Sggi defines a pre-maniplex but not a maniplex.
Premaniplex of rank 3 with 336 flags
gap> cg := ConnectionGroup(M);
<permutation group with 3 generators>
gap> NrMovedPoints(cg);
336
gap> NrMovedPoints(cg.1);
336
gap> NrMovedPoints(cg.2);
288
gap> NrMovedPoints(cg.3);
336
```

I'm guessing the definition of s1 in Lace (in map_operations.gi) has a minor omission.

**Comment by SupposeNot** [comment]
Was a bug in the s1 code. Fixed in f6b0526.
