### ISSUE TITLE
Bug in QuotientSggiByNormalSubgroup (Gap's fault)

### ISSUE THREAD

**Issue by CunningGabe** [SupposeNot/RAMP#173]
quotients.gi Line 357 - NaturalHomomorphismEtc is not respecting the generator order.
So let's fix that and maybe make our own utility for "generator-respecting natural homomorphism"

**Comment by SupposeNot** [comment]
Fixed in bc7480710ebe42c6f9cfbae64603362506e7d05a. Introduces function ReallyNaturalHomomorphismByNormalSubgroup.
