### ISSUE TITLE
Bug in QuotientManiplexByAutomorphismSubgroup

### ISSUE THREAD

**Issue by SupposeNot** [SupposeNot/RAMP#174]
```
gap> p:=ARP([5,2,3]);
AbstractRegularPolytope([ 5, 2, 3 ])
gap> aut:=AutomorphismGroupOnFlags(p);
<permutation group with 4 generators>
gap> cent:=Center(aut);
Group(())
gap> QuotientManiplexByAutomorphismSubgroup(p,cent);
4-maniplex with 0 flags
```
Pretty sure that if I quotient by the trivial subgroup I should get the original polytope back...

**Comment by CunningGabe** [comment]
Oops, I just saw that Mark added something to fix this. I think it might have also been broken in cases where h was nontrivial but had some fixed points, and that is now fixed in dd03071286625fa5cafc2bb19bb6ef3505d5fdb1.
