### ISSUE TITLE
Erroneous citation for SatisfiesWeakPathIntersectionProperty

### ISSUE THREAD

**Issue by SupposeNot** [SupposeNot/RAMP#183]
So... I wanted to read some more about this test involved in testing a maniplex for polytonality, but the cited paper ([GH18] Gleason, I. and Hubard, I., [Products of abstract polytopes](https://doi.org/10.1016%2Fj.jcta.2018.02.002), Journal of Combinatorial Theory, Series A, Elsevier {BV}, 157 (2018), 287--320.) does not appear to contain any reference to this property... sooo... where _does_ it come from?

**Comment by SupposeNot** [comment]
Poking around, there's a paper which seems more on point, but doesn't seem to have _exactly_ the right thing in it:
[1] J. Garza-Vargas and I. Hubard. Polytopality of maniplexes. Discrete Math., 341(7):2068–2079, 2018.
This has several path intersection properties, but none called the WPIP.

**Comment by CunningGabe** [comment]
What happened here is that in a preprint of their paper, they had two properties: the Weak PIP and the PIP. Later, they changed it, so the old WPIP is now called the PIP, and the old PIP is now called the Strong PIP. So we should rename the function(s) and then cite Polytopality of Maniplexes.

**Comment by SupposeNot** [comment]
I'll take care of it then...

**Comment by SupposeNot** [comment]
Handled in c30702c.
