### ISSUE TITLE
Revisit the display / view / print behavior of all basic objects

### ISSUE THREAD

**Issue by CunningGabe** [SupposeNot/RAMP#45]
Ideally, we want EvalString(Print(M)) to be equal to M.

For polytopes in ranks <= 2 it would be nice to have a standard view e.g. "10-gon" instead of "Rank 2 polytope of type [10] with 20 flags".

**Comment by CunningGabe** [comment]
For small edge labeled graphs, we might consider defaulting to just giving the list of labeled edges.

For maniplexes, I want to do some hard thinking, because there were some clever hacks I used that sometimes don't work the way I want. (Mostly the problem is that I want the display behavior to change as we learn more information, but then I can't store the display information as a string attribute, because there are protections against overwriting attribute values.)

**Comment by SupposeNot** [comment]
Need a checklist of basic objects to be reviewed before each major release.

**Comment by SupposeNot** [comment]
Moved to Wiki.
