### ISSUE TITLE
Implement the Wythoff operations as voltage operations

### ISSUE THREAD

**Issue by CunningGabe** [SupposeNot/RAMP#61]
We should look through the literature for whatever we can find on Wythoff operations, especially in higher rank. Then we can think about how to implement appropriately.

**Comment by Mixer2021** [comment]
Let me know if you think what I added is enough.
The bones are definitely there.

**Comment by CunningGabe** [comment]
I added some basic tests in 6d23fcc3df2823013a73e25e978eb1ee859448ae.
I think we can call this good enough for now.
