### ISSUE TITLE
Add example sessions and tests

### ISSUE THREAD

**Issue by SupposeNot** [SupposeNot/RAMP#80]
There's a lot of the code base where the documentation is lacking examples. This is OK in some cases, but should not be our default approach, and we should be providing examples anywhere it makes even a little bit of sense. For example, the documentation for ``ReflexibleManiplex`` and ``Maniplex`` are _pretty_ thin, and a couple examples would go a long way to making this stuff useful for people who don't want to spend quality time digging through the source code.

**Comment by CunningGabe** [comment]
Documentation and Examples are now all set for 0.7.

**Comment by SupposeNot** [comment]
So we should close this? I mean... if we have ever gotten a release where they all exist, it should then become a matter of incorporating to our development process that all new functions get documentation and a test added, instead of a standing item. Or this should somehow end up in the wiki. Maybe under a new page on "Development Best Practices" or something.

**Comment by CunningGabe** [comment]
OK, migrated to the wiki.
