### ISSUE TITLE
Add FacetList, SectionList, etc

### ISSUE THREAD

**Issue by CunningGabe** [SupposeNot/RAMP#96]
Unlike Facets, which only returns the facet types up to isomorphism, FacetList would return a list of facets _in situ_, with the flag numbering inherited directly from the maniplex. Requires #95.

**Comment by SupposeNot** [comment]
Trying to work on [Skeletal Polyhedra](https://github.com/SupposeNot/RAMP/issues/34) I realized I need something similar to *this* for implementing *that*.

**Comment by SupposeNot** [comment]
Implemented in [de273b7](https://github.com/SupposeNot/RAMP/commit/de273b74a71570f135098a96141d49bec5e0cbd9)].
